s = input()
print(f"英文字符: {sum(c.isalpha() for c in s)}")
print(f"数字: {sum(c.isdigit() for c in s)}")
print(f"空格: {sum(c.isspace() for c in s)}")
print(f"其他字符: {len(s)-sum(c.isalpha() or c.isdigit() or c.isspace() for c in s)}")
